# fly.toml app configuration file generated for nts-bot on 2024-11-01T01:48:08+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nts-bot"
primary_region = "mad"

[build]

[mounts]
  source = "pickle_data"
  destination = "/app/pickle_data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  count = 1